spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URI}
              predicates:
                - Path=/api/v1/users/**,/api/v1/cards/**
            - id: auth-service
              uri: ${AUTH_SERVICE_URI}
              predicates:
                - Path=/api/v1/auth/**
            - id: order-service
              uri: ${ORDER_SERVICE_URI}
              predicates:
                - Path=/api/v1/orders/**
server:
  port: 8086
jwt:
  secret: ${JWT_SECRET}
logging:
  level:
    org.springframework: DEBUG
